# -*- coding: utf-8 -*-
"""Pedra, papel e tesoura.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nm-el_5DoGIFG18grLM-229fUGjGkaWZ
"""

from random import randint
from time import sleep

itens = ("PEDRA" , "PAPEL" , "TESOURA")
pc = randint(0,2)


print(''' Suas opções :
[ 0 ] PEDRA
[ 1 ] PAPEL
[ 2 ] TESOURA ''')

jogador = int(input("Qual é a sua jogada ? "))



print("JÓÓÓ")
sleep(1)
print("KEN")
sleep(1)
print("POOOO")
sleep(1)

print('-='*11)

print(f"O computador jogou {itens[pc]}")
print(f"Você jogou {itens[jogador]}")

print('-='*11)


if pc == 0 and jogador == 0:
  print("empate")
elif pc == 1 and jogador == 1:
  print("empate")
elif pc == 2 and jogador == 2:
  print("empate")
else:
    ("Opção invalida")



if pc == 0:
  if jogador == 1:
    print("jogador venceu!!")
  elif jogador == 2:
    print("Computador venceu!!")
  else:
    ("Opção invalida")

if pc == 1:
  if jogador == 0:
    print("Computador venceu !!")
  elif jogador == 2:
    print("Jogaodor venceu!!")
  else:
    ("oplçao invalida")

if pc == 2:
  if jogador == 0:
    print("Jogador venceu!!")
  elif jogador == 1:
    print("Computador venceu !!")
else:
  ("opção invalida tente novamente")